about/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.about,
        name='about'
    ),
 ]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.cart_detail,
        name='cart_detail'
    ),

    url(
        regex=r'^add/(?P<product_id>\d+)/$',
        view=views.cart_add,
        name='cart_add'
    ),

    url(
        regex=r'^remove/(?P<product_id>\d+)/$',
        view=views.cart_remove,
        name='cart_remove'
    ),

]

eshopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from jet.dashboard.dashboard_modules import google_analytics_views


urlpatterns = i18n_patterns(
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^profile/', include('registration.urls', namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(_(r'^faq/'), include('faq.urls', namespace='faq')),
    url(_(r'^privacy/'), include('privacy-policy.urls', namespace='privacy')),
    url(_(r'^refund/'), include('refund-policy.urls', namespace='refund')),
    url(_(r'^about/'), include('about.urls', namespace='about')),
    url(_(r'^contact/'), include('contact.urls', namespace='contact')),
    url(_(r'coupons/'), include('coupons.urls', namespace='coupons')),
    url(_(r'^orders/'), include('orders.urls', namespace='orders')),
    url(_(r'^cart/'), include('cart.urls', namespace='cart')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(_(r'^payment/'), include('payment.urls', namespace='payment')),
    url(r"^search/", include("watson.urls", namespace="watson")),
    url(_(r'^onlineshop/'), include('onlineshop.urls', namespace='onlineshop')),
)

if settings.DEBUG:
            urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.faq,
        name='faq'
    ),
 ]

home/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views

urlpatterns = [
    url(
        regex=_(r'^$'),
        view=views.home,
        name='home'
    ),
 ]

newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

orders/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views


urlpatterns = [
    url(_(r'^create/$'), views.order_create, name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
]

newsletter/views.py
import logging

logger = logging.getLogger(__name__)

import datetime
import socket

from smtplib import SMTPException

from django.core.exceptions import ValidationError, ImproperlyConfigured
from django.core.urlresolvers import reverse
from django.conf import settings

from django.template.response import SimpleTemplateResponse

from django.shortcuts import get_object_or_404, redirect
from django.http import Http404

from django.views.generic import (
    ListView, DetailView,
    ArchiveIndexView, DateDetailView,
    TemplateView, FormView
)

from django.contrib import messages
from django.contrib.sites.models import Site
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils import timezone

from django.forms.models import modelformset_factory

from .models import Newsletter, Subscription, Submission
from .forms import (
    SubscribeRequestForm, UserUpdateForm, UpdateRequestForm,
    UnsubscribeRequestForm, UpdateForm
)
from .settings import newsletter_settings
from .utils import ACTIONS


class NewsletterViewBase(object):
    """ Base class for newsletter views. """
    queryset = Newsletter.on_site.filter(visible=True)
    allow_empty = False
    slug_url_kwarg = 'newsletter_slug'


class NewsletterDetailView(NewsletterViewBase, DetailView):
    pass


class NewsletterListView(NewsletterViewBase, ListView):
    """
    List available newsletters and generate a formset for (un)subscription
    for authenticated users.
    """

    def post(self, request, **kwargs):
        """ Allow post requests. """

        # All logic (for now) occurs in the form logic
        return super(NewsletterListView, self).get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(NewsletterListView, self).get_context_data(**kwargs)

        if self.request.user.is_authenticated():
            # Add a formset for logged in users.
            context['formset'] = self.get_formset()

        return context

    def get_formset(self):
        """
        Return a formset with newsletters for logged in users, or None.
        """

        # Short-hand variable names
        newsletters = self.get_queryset()
        request = self.request
        user = request.user

        SubscriptionFormSet = modelformset_factory(
            Subscription, form=UserUpdateForm, extra=0
        )

        # Before rendering the formset, subscription objects should
        # already exist.
        for n in newsletters:
            Subscription.objects.get_or_create(
                newsletter=n, user=user
            )

        # Get all subscriptions for use in the formset
        qs = Subscription.objects.filter(
            newsletter__in=newsletters, user=user
        )

        if request.method == 'POST':
            try:
                formset = SubscriptionFormSet(request.POST, queryset=qs)

                if not formset.is_valid():
                    raise ValidationError('Update form invalid.')

                # Everything's allright, let's save
                formset.save()

                messages.info(
                    request,
                    ugettext("Your changes have been saved.")
                )

            except ValidationError:
                # Invalid form posted. As there is no way for a user to
                # enter data - invalid forms should be ignored from the UI.

                # However, we log them for debugging purposes.
                logger.warning(
                    'Invalid form post received',
                    exc_info=True, extra={'request': request}
                )

                # Present a pristine form
                formset = SubscriptionFormSet(queryset=qs)

        else:
            formset = SubscriptionFormSet(queryset=qs)

        return formset


class ProcessUrlDataMixin(object):
    """
    Mixin providing the ability to process args and kwargs from url
    before dispatching request.
    """

    def process_url_data(self, *args, **kwargs):
        """ Subclasses should put url data processing in this method. """
        pass

    def dispatch(self, *args, **kwargs):
        self.process_url_data(*args, **kwargs)

        return super(ProcessUrlDataMixin, self).dispatch(*args, **kwargs)


class NewsletterMixin(ProcessUrlDataMixin):
    """
    Mixin retrieving newsletter based on newsletter_slug from url
    and adding it to context and form kwargs.
    """

    def process_url_data(self, *args, **kwargs):
        """
        Get newsletter based on `newsletter_slug` from url
        and add it to instance attributes.
        """

        assert 'newsletter_slug' in kwargs

        super(NewsletterMixin, self).process_url_data(*args, **kwargs)

        newsletter_queryset = kwargs.get(
            'newsletter_queryset',
            Newsletter.on_site.all()
        )
        newsletter_slug = kwargs['newsletter_slug']

        self.newsletter = get_object_or_404(
            newsletter_queryset, slug=newsletter_slug,
        )

    def get_form_kwargs(self):
        """ Add newsletter to form kwargs. """
        kwargs = super(NewsletterMixin, self).get_form_kwargs()

        kwargs['newsletter'] = self.newsletter

        return kwargs

    def get_context_data(self, **kwargs):
        """ Add newsletter to context. """
        context = super(NewsletterMixin, self).get_context_data(**kwargs)

        context['newsletter'] = self.newsletter

        return context


class ActionMixin(ProcessUrlDataMixin):
    """ Mixin retrieving action from url and adding it to context. """

    action = None

    def process_url_data(self, *args, **kwargs):
        """ Add action from url to instance attributes if not already set. """
        super(ActionMixin, self).process_url_data(*args, **kwargs)

        if self.action is None:
            assert 'action' in kwargs
            self.action = kwargs['action']

        assert self.action in ACTIONS, 'Unknown action: %s' % self.action

    def get_context_data(self, **kwargs):
        """ Add action to context. """
        context = super(ActionMixin, self).get_context_data(**kwargs)

        context['action'] = self.action

        return context

    def get_template_names(self):
        """ Return list of template names for proper action. """

        if self.template_name is None:
            raise ImproperlyConfigured(
                '%(class_name)s should define template_name, '
                'or implement get_template_names()' % {
                    'class_name': self.__class__.__name__
                }
            )

        else:
            try:
                return [self.template_name % {'action': self.action}]
            except KeyError as e:
                raise ImproperlyConfigured(
                    '%(class_name)s inherits from ActionMixin and can contain '
                    '%%(action)s in template_name to be replaced '
                    'by action name %(wrong_key)s given instead.' % {
                        'class_name': self.__class__.__name__,
                        'wrong_key': e,
                    }
                )


class ActionTemplateView(NewsletterMixin, ActionMixin, TemplateView):
    """
    View that renders a template for proper action,
    with newsletter and action in context.
    """
    pass


class ActionFormView(NewsletterMixin, ActionMixin, FormView):
    """ FormView with newsletter and action support. """

    def get_url_from_viewname(self, viewname):
        """
        Return url for given `viename`
        and associated with this view newsletter and action.
        """

        return reverse(
            viewname,
            kwargs={
                'newsletter_slug': self.newsletter.slug,
                'action': self.action
            }
        )


class ActionUserView(ActionTemplateView):
    """ Base class for subscribe and unsubscribe user views. """
    template_name = "newsletter/subscription_%(action)s_user.html"

    def process_url_data(self, *args, **kwargs):
        """ Add confirm to instance attributes. """
        super(ActionUserView, self).process_url_data(*args, **kwargs)

        # confirm is optional kwarg defaulting to False
        self.confirm = kwargs.get('confirm', False)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ActionUserView, self).dispatch(*args, **kwargs)


class SubscribeUserView(ActionUserView):
    action = 'subscribe'

    def get(self, request, *args, **kwargs):
        already_subscribed = False
        instance = Subscription.objects.get_or_create(
            newsletter=self.newsletter, user=request.user
        )[0]

        if instance.subscribed:
            already_subscribed = True
        elif self.confirm:
            instance.subscribed = True
            instance.save()

            messages.success(
                request,
                _('You have been subscribed to %s.') % self.newsletter
            )

            logger.debug(
                _('User %(rs)s subscribed to %(my_newsletter)s.'),
                {
                    "rs": request.user,
                    "my_newsletter": self.newsletter
                }
            )

        if already_subscribed:
            messages.info(
                request,
                _('You are already subscribed to %s.') % self.newsletter
            )

        return super(SubscribeUserView, self).get(request, *args, **kwargs)


class UnsubscribeUserView(ActionUserView):
    action = 'unsubscribe'

    def get(self, request, *args, **kwargs):
        not_subscribed = False

        try:
            instance = Subscription.objects.get(
                newsletter=self.newsletter, user=request.user
            )

newsletter/templates/newsletter/common.html
{% load static crispy_forms_tags %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/favi.gif' %}">

    <!-- Title -->
    <title>{% trans "E-Shopper" %} | {% block title %}{% endblock %}</title>

    <!-- Bootstrap Files and Plugins -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

   <!-- Crisp Live Chat -->
   <script type="text/javascript"> window.$crisp=[];window.CRISP_WEBSITE_ID="38d6144c-67a0-4b31-8cfb-2ee97bf4c905";(function(){ d=document;s=d.createElement("script"); s.src="https://client.crisp.chat/l.js"; s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})(); </script>
      
        {% block header %}
<header id="header"><!--header-->
        <div class="header_top"><!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="#"><i class="fa fa-phone"></i> +233 20 18 75 333</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> info@eshopper.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle"><!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="{% url 'home:home' %}"><img src="{% static 'img/logo.png' %}" alt="" /></a>
                        </div>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        <div class="btn-group pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    English
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    {% for language in languages %}
                                    <li><a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>{{ language.name }}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'profiles:profile_home' %}"><i class="fa fa-user"></i>{% trans "Account" %}</a></li>
                                <li><a href="{% url 'orders:order_create' %}"><i class="fa fa-crosshairs"></i>{% trans "Checkout" %}</a></li>
                                <li><a href="{% url "cart:cart_detail" %}">{{ total_items }}<i class="fa fa-shopping-cart"></i>{% trans "Cart" %}</a></li>
                                <li><a href="{% url 'auth_login' %}"><i class="fa fa-lock"></i>{% trans "Login" %}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom"><!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="{% url 'home:home' %}" class="active">{% trans "Home" %}</a></li>
                                <li><a href="{% url 'onlineshop:product_list' %}">{% trans "Shop" %}</a></li>
                                <li><a href="{% url 'about:about' %}">{% trans "About Us" %}</a></li>
                                <li><a href="{% url 'contact:contact' %}">{% trans "Contact Us" %}</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right" >
                            <form method="GET" action="">
                            <input type="text" name="q" placeholder="{% trans "Search Products" %}"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->


        {% endblock header %}
    </head>

<body class="animate-page" data-spy="scroll" data-target="#navbar" data-offset="100">
    <!--Preloader div-->
    <div class="preloader"></div>

<div class="container">
 <font color="black">
 <center>

        {% block body %}
        {% endblock body %}

 </center>
  </font>
</div>

<br />
     <center><p><a class="btn btn-lg btn-success" href="{% url 'home:home' %}" role="button">Go Back To E-Shopper Website</a></p></center>
<br />
    </body>
</html>

newsletter/templates/newsletter/newsletter_detail.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter detail" %}{% endblock title %}

{% block body %}
<table>
    <tr>
        <th>{% trans "Newsletter" %} {{ object.title }}</th>
    </tr>
    <tr>
        <td><a href="{% url "newsletter_subscribe_request" object.slug %}">Subscribe</a></td>
    </tr>
    {% if not user.is_authenticated %}
    <tr>
        <td><a href="{% url "newsletter_update_request" object.slug %}">Update</a></td>
    </tr>
    {% endif %}
    <tr>
        <td><a href="{% url "newsletter_unsubscribe_request" object.slug %}">Unsubscribe</a></td>
    </tr>
    <tr>
        <td><a href="{% url "newsletter_archive" object.slug %}">Archive</a></td>
    </tr>
    <tr>
        <td><a href="../">Back to list</a></td>
    </tr>
</table>
{% endblock body %}

newsletter/templates/newsletter/newsletter_list.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter list" %}{% endblock title %}

{% block body %}
{% if user.is_authenticated %}
<form method="POST" action="">
  {% csrf_token %}
  {{ formset.management_form }}
  <table>
    <tr>
        <th>{% trans "Newsletter" %}</th>
        {% if user %}
        <th>{% trans "Subscribe" %}</th>
        {% endif %}
    </tr>
    {% for form in formset.forms %}
      <tr>
        <td>{{ form.id }}{{ form.newsletter }}
<a href="{% url "newsletter_detail" form.instance.newsletter.slug %}">{{ form.instance.newsletter.title }}</a></td>
        <td>{{ form.subscribed }}</td>
      </tr>
    {% endfor %}
  </table>
  <p><input id="id_submit" name="submit" value="{% trans "Update subscriptions" %}" type="submit" /></p>
</form>
{% else %}
<table>
    <tr>
        <th>{% trans "Newsletter" %}</th>
    </tr>
    {% for newsletter in object_list %}
    <tr>
        <td><a href="{% url "newsletter_detail" newsletter.slug %}">{{ newsletter.title }}</a></td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock body %}

newsletter/templates/newsletter/submission_archive.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter archive" %}{% endblock title %}

{% block body %}
<table>
    <tr>
        <th>{% trans "Newsletter archive" %} {{ newsletter.title }}</th>
    </tr>
    {% for submission in latest %}
    <tr>
        <td><a href="{{ submission.get_absolute_url }}">{{ submission }}</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td><a href="../">Back to list</a></td>
    </tr>
</table>
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe.html
{% extends "newsletter/common.html" %}
{% load static crispy_forms_tags %}
{% load i18n %}

{% block title %}{% trans "Newsletter subscribe" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter subscribe" %} {{ newsletter.title }}</h1>

    {% if error %}
        <p>{% trans "Due to a technical error we were not able to submit your confirmation email. This could be because your email address is invalid." %}</p>

        {% comment %} Replace the the following dummy with a valid email address and remove this comment.

        <p>{% trans "If the error persists, please don't hesitate to contact us at the following email address:" %} <a href="mailto:paawilly17@gmail.com">paawilly17@gmail.com</a></p>

        {% endcomment %}
    {% else %}
        <form enctype="multipart/form-data" method="post" action=".">
            {% csrf_token %}
            {{ form|crispy }}
            <p><center></center><input id="id_submit" name="submit" class="btn btn btn-success" value="{% trans "Subscribe" %}" type="submit" /></center></p>
        </form>
    {% endif %}
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe_activated.html
{% extends "newsletter/common.html" %}

{% load i18n %}


{% block title %}
{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}
{% endblock title %}


{% block body %}
<br><br><br><br><br><br>
<section>
   
 <div class="col-md-12">
       
 <div class="panel panel-danger wow fadeInLeft">
          
  <div class="container">
    			
<div class="row ">
                      
  <h5 class="page-title wow fadeInDown">{{ newsletter.title }} Newsletter Activation<br></h5><br>

  
                      <div class="col-xs-15">
                      
      <p>Your subscription has successfully been activated. Thanks</p><br>
   
                     </div>
                </div>
            </div>
        </div>
    
</div>
</section><br><br><br><br><br>
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe_email_sent.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter subscribe" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter subscribe" %} {{ newsletter.title }}</h1>

    <p>{% trans "Your subscription request was successfully received and an activation email has been sent to you. In that email you will find a link which you need to follow in order to activate your subscription." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_subscribe_user.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter subscribe" %}{% endblock title %}

{% block body %}
<h1>{% trans "Newsletter subscribe" %} {{ newsletter.title }}</h1>

<p>Welcome, {{ user }}!</p>

{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% else %}
{% trans "Do you want to subscribe to this newsletter?" %}
<form enctype="multipart/form-data" method="post" action="{% url "newsletter_subscribe_confirm" newsletter.slug %}">
    {% csrf_token %}
    <p><center><input id="id_submit" name="submit" value="{% trans "Subscribe" %}" type="submit" /></center></p>
</form>
{% endif %}
{% endblock body %}

newsletter/templates/newsletter/subscription_unsubscribe_activated.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter" %} {{ newsletter.title }} {{ action }} {% trans "activate" %}</h1>

    <p>{% trans "You have successfully been unsubscribed." %}</p>
{% endblock body %}

newsletter/templates/newsletter/subscription_unsubscribe_email_sent.html
{% extends "newsletter/common.html" %}

{% load i18n %}

{% block title %}{% trans "Newsletter unsubscribe" %}{% endblock title %}

{% block body %}
    <h1>{% trans "Newsletter unsubscribe" %} {{ newsletter.title }}</h1>

    <p>{% trans "Your unsubscription request has successfully been received. An email has been sent to you with a link you need to follow in order to confirm your unsubscription." %}</p>
{% endblock body %}