cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.cart_detail,
        name='cart_detail'
    ),

    url(
        regex=r'^add/(?P<product_id>\d+)/$',
        view=views.cart_add,
        name='cart_add'
    ),

    url(
        regex=r'^remove/(?P<product_id>\d+)/$',
        view=views.cart_remove,
        name='cart_remove'
    ),

]

coupons/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views

urlpatterns = [
    url(
        regex=_(r'^apply/$'),
        view=views.coupon_apply,
        name='apply'
    ),
]

eshopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from jet.dashboard.dashboard_modules import google_analytics_views


urlpatterns = i18n_patterns(
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^profile/', include('registration.urls', namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(_(r'^faq/'), include('faq.urls', namespace='faq')),
    url(_(r'^privacy/'), include('privacy-policy.urls', namespace='privacy')),
    url(_(r'^refund/'), include('refund-policy.urls', namespace='refund')),
    url(_(r'^about/'), include('about.urls', namespace='about')),
    url(_(r'^contact/'), include('contact.urls', namespace='contact')),
    url(_(r'coupons/'), include('coupons.urls', namespace='coupons')),
    url(_(r'^orders/'), include('orders.urls', namespace='orders')),
    url(_(r'^cart/'), include('cart.urls', namespace='cart')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(_(r'^payment/'), include('payment.urls', namespace='payment')),
    url(r"^search/", include("watson.urls", namespace="watson")),
    url(_(r'^onlineshop/'), include('onlineshop.urls', namespace='onlineshop')),
)

if settings.DEBUG:
            urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.faq,
        name='faq'
    ),
 ]

newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

onlineshop/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views

urlpatterns = [
    url(
        regex=_(r'^product_list/$'),
        view=views.product_list,
        name='product_list'
    ),

    url(
        regex=r'^(?P<category_slug>[-\w]+)/$',
        view=views.product_list,
        name='product_list_by_category'
    ),

    url(
        regex=r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        view=views.product_detail,
        name='product_detail'),

]

orders/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views


urlpatterns = [
    url(_(r'^create/$'), views.order_create, name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from coupons.forms import CouponApplyForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from onlineshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from onlineshop.recommender import Recommender


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    coupon_apply_form = CouponApplyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products,
                                                  max_results=4)
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form,
                                                'recommended_products': recommended_products})

cart/templates/cart/detail.html
{% extends "onlineshop/base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
     {% trans "Cart" %}
{% endblock %}


{% block content %}
    <div id="content">
    <h1>{% trans "Your shopping cart" %}</h1>
    <table class="cart" >
        <thead>
            <tr>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Product" %}</th>
                <th>{% trans "Quantity" %}</th>
                <th>{% trans "Remove" %}</th>
                <th>{% trans "Unit price" %}</th>
                <th>{% trans "Price" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url}}
                                          {% else %}
                                                 {% static "img/no_image.png" %}
                                          {% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="{% trans "Update" %}">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td><a href="{% url "cart:cart_remove" product.id %}">{% trans "Remove" %}</a></td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
        {% endfor %}

        {% if cart.coupon %}
            <tr class="subtotal">
                <td>{% trans "Subtotal" %}</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
            <tr>
                {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                    <td>"{{ code }}" coupon ({{ discount }}% off)</td>
                {% endblocktrans %}
                <td colspan="4"></td>
                <td class="num neg">
                - ${{ cart.get_discount|floatformat:"2" }}
                </td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>{% trans "Total" %}</td>
            <td colspan="4"></td>
            <td class="num">
            ${{ cart.get_total_price_after_discount|floatformat:"2" }}
            </td>
        </tr>
      </tbody>
    </table>
    <p>{% trans "Apply a coupon" %}:</p>
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form}}
        <input type="submit" value="{% trans "Apply" %}">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url "onlineshop:product_list" %}" class="button light">{% trans "Continue shopping" %}</a>
        <a href="{% url "orders:order_create" %}" class="button">
           {% trans "Proceed To Checkout" %}
        </a>
    </p>
    </div>

    <br /><br /><br /><br/>

   {% if recommended_products %}
    <div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">{% trans "People who bought this also bought" %}</h2>
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">
                                 {% for p in recommended_products %}
									<div class="col-sm-4">
										<div class="product-image-wrapper1">
											<div class="single-products">
												<div class="productinfo text-center">
													 <a href="{{ p.get_absolute_url }}">
                                                         <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></a>
													<br />
													<p><strong><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></strong></p>
												</div>
											</div>
										</div>
									</div>
                                     {% endfor %}
								</div>

								<div class="item">
                                {% for p in recommended_products %}
									<div class="col-sm-4">
										<div class="product-image-wrapper1">
											<div class="single-products">
												<div class="productinfo text-center">
													 <a href="{{ p.get_absolute_url }}">
                                                         <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></a>
													<br />
													<p><strong><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></strong></p>
												</div>
											</div>
										</div>
									</div>
                                {% endfor %}

								</div>
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>
						</div>
					</div><!--/recommended_items-->
{% endif %}

{% endblock %}